version: '3.8'

services:configs:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuarios
      MYSQL_USER: juanma
      MYSQL_PASSWORD: bananaman

usuarios:
  depends_on:
    - db
  imagen: usuarios:latest
  volumes:
    - ./src/themes:/var/www/html/wp-content/themes
    - ./src/plugins:/var/www/html/wp-content/plugins
    - ./src/uploads:/var/ww/html/wp-content/uploads
  ports:
    - "8000:80"
  restart: always
  environment:
    USUARIOS_DB_HOST: db
    USUARIOS_DB_USER: juanma
    USUARIOS_DB_PASSWORD: bananaman
    USUARIOS_DB_NAME: usuarios